apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: traefik
spec:
  controllerName: traefik.io/gateway-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gourmetgram-gateway-controller
  namespace: gourmetgram-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gourmetgram-gateway-controller
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods","nodes","secrets","namespaces"]
  verbs: ["get","list","watch"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get","list","watch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gatewayclasses","gateways","httproutes","referencegrants","tcproutes","tlsroutes","grpcroutes"]
  verbs: ["get","list","watch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gatewayclasses/status","gateways/status","httproutes/status","tcproutes/status","tlsroutes/status","grpcroutes/status"]
  verbs: ["update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gourmetgram-gateway-controller
subjects:
- kind: ServiceAccount
  name: gourmetgram-gateway-controller
  namespace: gourmetgram-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gourmetgram-gateway-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gourmetgram-gateway-controller
  namespace: gourmetgram-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gourmetgram-gateway
  template:
    metadata:
      labels:
        app: gourmetgram-gateway
    spec:
      serviceAccountName: gourmetgram-gateway-controller
      containers:
      - name: traefik
        image: traefik:v3.1
        args:
        - --providers.kubernetesgateway=true
        - --entrypoints.web.address=:8000
        - --log.level=DEBUG
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gourmetgram-gateway
  namespace: gourmetgram-platform
spec:
  selector:
    app: gourmetgram-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8000
  externalIPs:
  - {{ .Values.gateway.externalIP }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gourmetgram-gateway
  namespace: gourmetgram-platform
spec:
  gatewayClassName: traefik
  listeners:
  - name: web
    port: 8000
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All

