apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gourmetgram-route
  namespace: gourmetgram-platform
spec:
  parentRefs:
  - name: gourmetgram-gateway
  hostnames:
  - gourmetgram.example.com
  rules:
  - backendRefs:
    - name: gourmetgram-app
      namespace: gourmetgram-production
      port: 80
      weight: 90
    - name: gourmetgram-app
      namespace: gourmetgram-canary
      port: 80
      weight: 10

