apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: gourmetgram-route
  namespace: gourmetgram-platform
spec:
  parentRefs:
  - name: gourmetgram-gateway
  rules:
  - backendRefs:
    - name: gourmetgram-app
      namespace: gourmetgram-production
      port: 8080
      weight: 90
    - name: gourmetgram-app
      namespace: gourmetgram-canary
      port: 8081
      weight: 10

