# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gourmetgram-app
  namespace: gourmetgram-production
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gourmetgram-app
  template:
    metadata:
      labels:
        app: gourmetgram-app
    spec:
      containers:
        - name: gourmetgram-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: gourmetgram-app
  namespace: gourmetgram-production
spec:
  selector:
    app: gourmetgram-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  externalIPs:
    - {{ .Values.service.externalIP }}
---
# ReferenceGrant allows HTTPRoute in gourmetgram-platform to reference this Service
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-platform-httproute
  namespace: gourmetgram-production
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: gourmetgram-platform
  to:
  - group: ""
    kind: Service

