replicaCount: 1

image:
  repository: registry.kube-system.svc.cluster.local:5000/gourmetgram-app
  tag: canary-1.0.0

service:
  port: 8081
  externalIP: ""   # Placeholder

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
